version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "donutor"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "asdqwe123"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"